# Copyright © 2018 AT&T USA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


cloud_config:
  identity_services:
    DEFAULT_KEYSTONE:
      identity_url: http://192.168.35.52:5000/v2.0
      mso_id: admin
      mso_pass: admin
      admin_tenant: service
      member_role: admin
      tenant_metadata: true
      identity_server_type: KEYSTONE
      identity_authentication_type: USERNAME_PASSWORD
      project_domain_name: service
      user_domain_name: admin
  cloud_sites:
    RegionOne:
      region_id: RegionOne
      clli: RegionOne
      identity_service_id: DEFAULT_KEYSTONE


server:
    port: ${CONTAINER_PORT}
    tomcat:
        max-threads: 50
ssl-enable: false
mso:
  logPath: logs
  site-name: onapheat
  catalog:
    db:
      spring:
        endpoint: http://catalog-db-adapter.${COMMON_NAMESPACE}:8082
  db:
    auth: Basic YnBlbDpwYXNzd29yZDEk

spring:
  datasource:
     hikari:
       jdbcUrl: jdbc:mariadb://${DB_HOST}:${DB_PORT}/catalogdb
       username: ${DB_USERNAME}
       password: ${DB_PASSWORD}
       driver-class-name: org.mariadb.jdbc.Driver
       pool-name: catdb-pool
       registerMbeans: true

  flyway:
    baseline-on-migrate: false
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/catalogdb
    user: ${DB_ADMIN_USERNAME}
    password: ${DB_ADMIN_PASSWORD}
    outOfOrder: true
    validateOnMigrate: false
  jpa:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: validate
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        enable-lazy-load-no-trans: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true

#Actuator
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
